//
//  PSNetAtmoNotifications.h
//  PSNetAtmo
//
//  Created by Philip Schneider on 05.12.13.
//  Copyright (c) 2013 phschneider.net. All rights reserved.
//

#ifndef PSNetAtmo_PSNetAtmoNotifications____FILEEXTENSION___
#define PSNetAtmo_PSNetAtmoNotifications____FILEEXTENSION___

#define PSNETATMO_API_DATA_RECEIVED   @"PSNETATMO_API_DATA_RECEIVED"

// API
#define PSNETATMO_RECEIVED_AUTH_URL             @"PSNETATMO_RECEIVED_AUTH_URL"
#define PSNETATMO_RECEIVED_REDIRECT_URL         @"PSNETATMO_RECEIVED_REDIRECT_URL"

// ACOUNT
#define PSNETATMO_ACCOUNT_UPDATE_NOTIFICATION   @"PSNETATMO_ACCOUNT_UPDATE_NOTIFICATION"

// DEVICE
#define PSNETATMO_DEVICE_UPDATE_NOTIFICATION    @"PSNETATMO_DEVICE_UPDATE_NOTIFICATION"

// UPDATE
#define PSNETATMO_USER_UPDATE_NOTIFICATION          @"PSNETATMO_USER_UPDATE_NOTIFICATION"
#define PSNETATMO_RESET_CURRENT_USER_NOTIFICATION   @"PSNETATMO_RESET_CURRENT_USER_NOTIFICATION"
#define PSNETNETATMO_SET_CURRENT_USER_NOTIFICATION  @"PSNETNETATMO_SET_CURRENT_USER_NOTIFICATION"
#define PSNETATMO_UPDATED_DEVICES_NOTIFICATION      @"PSNETATMO_UPDATED_DEVICES_NOTIFICATION"

// PUBLIC
#define PSNETATMO_PUBLIC_MEASURES_UPDATE_NOTIFICATION   @"PSNETATMO_PUBLIC_MEASURES_UPDATE_NOTIFICATION"
#define PSNETATMO_PUBLIC_DEVICE_ADDED_NOTIFICATION      @"PSNETATMO_PUBLIC_DEVICE_ADDED_NOTIFICATION"
#define PSNETATMO_PUBLIC_CLEAR_STORAGE                  @"PSNETATMO_PUBLIC_CLEAR_STORAGE"
#define PSNETATMO_PUBLIC_CLEAR_MAP                      @"PSNETATMO_PUBLIC_CLEAR_MAP"
#define PSNETATMO_PUBLIC_CLEAR_ALL                      @"PSNETATMO_PUBLIC_CLEAR_ALL"


#define PSNETATMO_NOTIFICATIONS     @[PSNETATMO_API_DATA_RECEIVED, PSNETATMO_RECEIVED_AUTH_URL, PSNETATMO_ACCOUNT_UPDATE_NOTIFICATION, PSNETATMO_DEVICE_UPDATE_NOTIFICATION, PSNETATMO_USER_UPDATE_NOTIFICATION, PSNETATMO_USER_UPDATE_NOTIFICATION, PSNETATMO_PUBLIC_MEASURES_UPDATE_NOTIFICATION, PSNETATMO_PUBLIC_DEVICE_ADDED_NOTIFICATION]

// MAP
#define PSNETATMO_PUBLIC_MAP_CHANGED_NOTIFICATION       @"PSNETATMO_PUBLIC_MAP_CHANGED_NOTIFICATION"
#define PSNETATMO_PUBLIC_MAP_UPDATED_USER_LOCATION      @"PSNETATMO_PUBLIC_MAP_UPDATED_USER_LOCATION"
#define PSNETATMO_API_UPDATE_FILTER                     @"PSNETATMO_API_UPDATE_FILTER"

#define PSNETATMO_PUBLIC_FIRST_START_NOTIFICATION       @"PSNETATMO_PUBLIC_FIRST_START_NOTIFICATION"

// ERRORS
#define PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_SERVICES_NOT_ENABLED    @"PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_SERVICES_NOT_ENABLED"
#define PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_AUTH_RESTRICTED         @"PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_AUTH_RESTRICTED"
#define PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_AUTH_DENIED             @"PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_AUTH_DENIED"
#define PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_UNKNOWN_ERROR           @"PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_UNKNOWN_ERROR"

#define PSNETATMO_MAP_NOTIFICATIONS     @[PSNETATMO_PUBLIC_MAP_CHANGED_NOTIFICATION, PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_UNKNOWN_ERROR, PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_AUTH_DENIED, PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_SERVICES_NOT_ENABLED,PSNETATMO_PUBLIC_MAP_ERROR_LOCATION_AUTH_RESTRICTED]



#endif
